[features]
seeds = false
[programs.localnet]
charity_sol = "8S9X2NND2gWutYFYPc8QUCv4zEbr9TDVsHufMR49YhYF"

[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "localnet"
wallet = "/home/mg/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
